name: flutter_bees2biz
description: Proyecto para medir mis conocimientos tecnicos en Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    #back-end
  provider: ^4.3.3
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
    
    #front-end
  cupertino_icons: ^1.0.0
  animate_do: ^1.7.5
  material_floating_search_bar: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
